import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-rows-[200px_1fr_100px] min-h-screen">
          <div className="bg-purple-500 text-white p-4">200px</div>
          <div className="bg-green-500 text-white p-4">Flexível</div>
          <div className="bg-orange-500 text-white p-4">100px</div>
        </div>
        {/*children*/}
      </body>
    </html>
  );
}
